version: '3'

services:
  mysql:
    image: mysql
    container_name: mysql_container
    volumes:
      - /var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: mediscreen-patients
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    restart: on-failure
    networks:
      - microservices-network

  mongodb:
    image: mongo:7 #:7.0.0
    container_name: mongodb_container
    volumes:
      - /data/db
    ports:
      - "27017:27017"
    restart: on-failure
    networks:
      - microservices-network

  patient:
    build: ./service-patient
    depends_on:
      - mysql
    image: ms-patient
    container_name: patient_container
    environment:
      - "spring_datasource_username=root"
      - "spring_datasource_password=root"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mediscreen-patients?createDatabaseIfNotExist=true&serverTimezone=UTC"
      - "SPRING_DATABASE_PORT: 3306"
      - "SLEEP_LENGTH=5"
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - microservices-network

  notes:
    build: ./service-notes
    depends_on:
      - mongodb
    image: ms-notes
    container_name: notes_container
    environment:
      - "spring_data_mongodb_host=mongodb"
      - "SPRING_DATASOURCE_URL: mongodb://127.0.0.1:27017/mediscreen-notes"
      - "SPRING_DATABASE_PORT: 27017"
    ports:
      - "8082:8082"
    networks:
      - microservices-network

  report:
    build: ./service-report
    depends_on:
      - mysql
      - mongodb
    image: ms-report
    container_name: report_container
    ports:
      - "8083:8083"
    networks:
      - microservices-network


  client:
    build: ./service-client
    image: ms-client
    container_name: client_container
    ports:
      - "8080:8080"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge